travis:
  secure:
    BINSTAR_TOKEN: l7ziCPkPZgPHbvZxGFRelPHUUUtvQ+ZtPnNbAgEfZ01bXo3bQuflBCK3mRIatCAsfuQthKCFkrwpQH7N2dNDjdXqRf/vNmPIxsJTAj/BwhBYp4SxM9dN9LFGweQVyxrBUgrZ4fk0XBJJbMSZD87CMijbJVSKogrGY40SCwQ5RaTcfmCieeFQ4fHG8hi4iooCL4xl3FBVr5bADPmPcz24/NjABu50z9VhTyshgECKiYedr5ppIXGfGyZWMoBR6M2IxP6QUgG84bPWsXeDKIheKWd4lY3NTYsAuSYpHXrG7LncNozmg/ZZ/uLLr2S4HKHAgkhRBG9woNvJBNU+O+NccjaIXFKc2GPD1btv+pUnmHMExxZ69hAJW5n1By41hNei2a+LAWaT+P6BWonBSbynXc6xmNzLDS6b6OAAgsH3wCku8+znZZpeuZn4TIVvKjec3wIgXBTwrVfBwS65GYYQOWFHBppWt8S0s9auPg5nXVfXcqvB/Ed6dOeTykkxZOZrmb5dIal5NIrfp2AF/L5EtQz4afo8yu8+4dRZzTk3z5+zF+UpvBDSo3WlPVU3/b6ilmVhEsT0/meT9tbSAKEH6ZHKnHo7KZG98nerUB6wPoxlPcx7yVGKHOGFApu/bBb6HMmBWGh2ul5/I6pD3UpM0zKuFknzVrIypI0XbC7Z5us=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
