travis:
  secure:
    BINSTAR_TOKEN: kI64IhDnMgg5hosvKKnIdScJw3y5CHIGC56spir9hHK6MjGi84swGo6aTanxe5JXrWJdGtBXe7TO5Bnmx0qSFj/73Y8XiGH87JmUOyZe2tQHoyEaWWxUDounWNSmG4wMxPrBHimVT/KMiqlKnb9cQZ2EQIZ3MCGw06xe0fm+GsDY6P8u8fozsugAGjKOYzfckshPobzhS2dG3Runsqzw1M/0h+VRqe93ofZ1DppSvsSVzan+NBRwP2bu0C5JvVvuZsbKsIJGo0msAWqvbOuHnvEc6Owu+bk+IEN03C7RdQkEMCUN61iUqgvh0GtoGOzXeqnAJvMNWCe4GCyCMsjoTcNJ4VJaZWNDqTpgiBqerz5UMgaBsDRMSVpEE2thlSjzS8BPYVrElcjWknDLYODtk2HRsFiNhpz7dWyRBKh1fxyw/UtZxQ6ixXD8x3NOwE2JFkwcOaxdh+KKG6jZyS8YnCGTRtGq97gFpvitfpaBUYFbuE/l6BZnQfvQz+hzvpTQEMi1prKndI88u0MpmEWEz41bYerelLUPT74BGfZMx8Zio9uRKXfgK4h0P+XhcB1u/EsZdK1z77695WTbxHoMIYHj7mAXv5vRxZWR1aUqHeQdNCW6b67qZkjTUyR4R7VcxpAneWhlV+5OswW2rggF68HG9C5l3CrEHTOqfQtiK5s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
